<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PDO</title>
</head>
<body>
    <section>
        <h1>Liste des Employées</h1>

        <table>
            <thead>
                <tr>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Fonction</th>
                    <th>Ville</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($employees as $employee): ?>
                    <tr>
                        <td><?= $employee['firstName'] ?></td>
                        <td><?= $employee['lastName'] ?></td>
                        <td><?= $employee['jobTitle'] ?></td>
                        <td><?= $employee['city'] ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </section>
</body>
</html>